(1) add --enable-grid-system and (2) prepare to move to a new framework.
git-svn-id: http://mangos.svn.sourceforge.net/svnroot/mangos@198 26674162-90ff-0310-a85b-b64107c8dee9

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -468,7 +468,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INCLUDES LDFLAGS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE RANLIB ac_ct_RANLIB build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO CPP EGREP LIBTOOL LIBOBJS ALLOCA LINKER_OPTIONS COMPILER_OPTIONS EXTRA_LINKER_OPTIONS EXTRA_COMPILER_OPTIONS MANGOSD_CONFIG MANGOSD_DATA LT_RELEASE LT_CURRENT LT_AGE LT_REVISION LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INCLUDES LDFLAGS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE RANLIB ac_ct_RANLIB build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO CPP EGREP LIBTOOL LIBOBJS ALLOCA NEWFRAMEWORK_TRUE NEWFRAMEWORK_FALSE LINKER_OPTIONS COMPILER_OPTIONS EXTRA_LINKER_OPTIONS EXTRA_COMPILER_OPTIONS MANGOSD_CONFIG MANGOSD_DATA LT_RELEASE LT_CURRENT LT_AGE LT_REVISION LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1026,6 +1026,8 @@ Optional Features:
   --enable-static=PKGS  build static libraries default=yes
   --enable-fast-install=PKGS  optimize for fast installation default=yes
   --disable-libtool-lock  avoid locking (might break parallel builds)
+--enable-grid-system Turn on grid system
+--enable-new-framework Enable new framework
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -4853,7 +4855,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4856 "configure"' > conftest.$ac_ext
+  echo '#line 4858 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5382,7 +5384,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5385: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5387: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6566,7 +6568,7 @@ linux-gnu*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*)
-    echo '#line 6569 "configure"' > conftest.$ac_ext
+    echo '#line 6571 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7238,7 +7240,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7241 "configure"
+#line 7243 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7336,7 +7338,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7339 "configure"
+#line 7341 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11230,6 +11232,59 @@ fi;
 echo "$as_me:$LINENO: result: $MANGOSD_DEBUG_INFO" >&5
 echo "${ECHO_T}$MANGOSD_DEBUG_INFO" >&6
 
+# check for grid system enable
+echo "$as_me:$LINENO: checking whether grid system is enabled" >&5
+echo $ECHO_N "checking whether grid system is enabled... $ECHO_C" >&6
+MANGOSD_ENABLE_GRID=no
+# Check whether --enable-grid-system or --disable-grid-system was given.
+if test "${enable_grid_system+set}" = set; then
+  enableval="$enable_grid_system"
+
+    if test "$enableval" = "yes" ; then
+	CFLAGS="-DENABLE_GRID_SYSTEM $CFLAGS"
+	CXXFLAGS="-DENABLE_GRID_SYSTEM $CXXFLAGS"
+	MANGOSD_ENABLE_GRID=yes
+    elif test "$withval" != "no" ; then
+	{ { echo "$as_me:$LINENO: error: Please choose yes or no" >&5
+echo "$as_me: error: Please choose yes or no" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
+fi;
+echo "$as_me:$LINENO: result: $MANGOSD_ENABLE_GRID" >&5
+echo "${ECHO_T}$MANGOSD_ENABLE_GRID" >&6
+
+# check for enable new framework
+echo "$as_me:$LINENO: checking whether new framework is enabled" >&5
+echo $ECHO_N "checking whether new framework is enabled... $ECHO_C" >&6
+MANGOSD_ENABLE_NEW_FRAMEWORK=no
+# Check whether --enable-new-framework or --disable-new-framework was given.
+if test "${enable_new_framework+set}" = set; then
+  enableval="$enable_new_framework"
+
+    if test "$enableval" = "yes" ; then
+	MANGOSD_ENABLE_NEW_FRAMEWORK=yes
+    elif test "$withval" != "no" ; then
+	{ { echo "$as_me:$LINENO: error: Please choose yes or no" >&5
+echo "$as_me: error: Please choose yes or no" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
+fi;
+echo "$as_me:$LINENO: result: $MANGOSD_ENABLE_NEW_FRAMEWORK" >&5
+echo "${ECHO_T}$MANGOSD_ENABLE_NEW_FRAMEWORK" >&6
+
+
+if test x$MANGOS_ENABLE_NEW_FRAMEWORK = x$yes; then
+  NEWFRAMEWORK_TRUE=
+  NEWFRAMEWORK_FALSE='#'
+else
+  NEWFRAMEWORK_TRUE='#'
+  NEWFRAMEWORK_FALSE=
+fi
+
+
+
 if test $sysconfdir = '${prefix}/etc'; then
 	MANGOSD_CONFIG_TEMP="/etc/mangos/mangosd.conf"
 else
@@ -11375,6 +11430,13 @@ if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"AMDEP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${NEWFRAMEWORK_TRUE}" && test -z "${NEWFRAMEWORK_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"NEWFRAMEWORK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"NEWFRAMEWORK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -11977,6 +12039,8 @@ s,@EGREP@,$EGREP,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@ALLOCA@,$ALLOCA,;t t
+s,@NEWFRAMEWORK_TRUE@,$NEWFRAMEWORK_TRUE,;t t
+s,@NEWFRAMEWORK_FALSE@,$NEWFRAMEWORK_FALSE,;t t
 s,@LINKER_OPTIONS@,$LINKER_OPTIONS,;t t
 s,@COMPILER_OPTIONS@,$COMPILER_OPTIONS,;t t
 s,@EXTRA_LINKER_OPTIONS@,$EXTRA_LINKER_OPTIONS,;t t
